---
AWSTemplateFormatVersion: '2010-09-09'
Resources:

  # VPC Setup
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'false'
      Tags:
      # param
      - Key: Name
        Value: trial-vpc

# Private Subnet setup
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      # param
      AvailabilityZone: eu-west-1c
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        # param (+ concatinate az and cidr block at the end)
        Value: trial_priv_subnet

# Internet Gateway setup
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        # param
        Value: trial_ig

# Private Security Group setup
  PrivateSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Privately set up security group
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: Private_Trial_SG

# Route Tables setup
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Name
        Value: trial_priv_rt
  
  # Attaching IG to VPC
  gw1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

# Attach Gateways to Route Tables
  route1:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: PrivateRouteTable
      GatewayId:
        Ref: InternetGateway
    DependsOn: gw1

# Attach Route Tables to Subnets
  subnetroute3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PrivateSubnet

Outputs:
  PrivSG:
    Description: Private Subnet created
    Value: !Ref PrivateSg
    Export:
      Name: PrivateSG
  PrivSub:
    Description: Private Subnet created
    Value: !Ref PrivateSubnet
    Export:
      Name: PrivateSub
